//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab7b.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Telephone", Namespace="http://schemas.datacontract.org/2004/07/WCF.Models")]
    [System.SerializableAttribute()]
    public partial class Telephone : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string surnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int number {
            get {
                return this.numberField;
            }
            set {
                if ((this.numberField.Equals(value) != true)) {
                    this.numberField = value;
                    this.RaisePropertyChanged("number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                if ((object.ReferenceEquals(this.surnameField, value) != true)) {
                    this.surnameField = value;
                    this.RaisePropertyChanged("surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IMyService")]
    public interface IMyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetDict", ReplyAction="http://tempuri.org/IMyService/GetDictResponse")]
        Lab7b.ServiceReference.Telephone[] GetDict();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetDict", ReplyAction="http://tempuri.org/IMyService/GetDictResponse")]
        System.Threading.Tasks.Task<Lab7b.ServiceReference.Telephone[]> GetDictAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetAll", ReplyAction="http://tempuri.org/IMyService/GetAllResponse")]
        string GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetAll", ReplyAction="http://tempuri.org/IMyService/GetAllResponse")]
        System.Threading.Tasks.Task<string> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/AddDict", ReplyAction="http://tempuri.org/IMyService/AddDictResponse")]
        string AddDict(string surname, int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/AddDict", ReplyAction="http://tempuri.org/IMyService/AddDictResponse")]
        System.Threading.Tasks.Task<string> AddDictAsync(string surname, int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/UpdDict", ReplyAction="http://tempuri.org/IMyService/UpdDictResponse")]
        string UpdDict(int id, string surname, int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/UpdDict", ReplyAction="http://tempuri.org/IMyService/UpdDictResponse")]
        System.Threading.Tasks.Task<string> UpdDictAsync(int id, string surname, int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/DelDict", ReplyAction="http://tempuri.org/IMyService/DelDictResponse")]
        string DelDict(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/DelDict", ReplyAction="http://tempuri.org/IMyService/DelDictResponse")]
        System.Threading.Tasks.Task<string> DelDictAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyServiceChannel : Lab7b.ServiceReference.IMyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyServiceClient : System.ServiceModel.ClientBase<Lab7b.ServiceReference.IMyService>, Lab7b.ServiceReference.IMyService {
        
        public MyServiceClient() {
        }
        
        public MyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Lab7b.ServiceReference.Telephone[] GetDict() {
            return base.Channel.GetDict();
        }
        
        public System.Threading.Tasks.Task<Lab7b.ServiceReference.Telephone[]> GetDictAsync() {
            return base.Channel.GetDictAsync();
        }
        
        public string GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<string> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public string AddDict(string surname, int number) {
            return base.Channel.AddDict(surname, number);
        }
        
        public System.Threading.Tasks.Task<string> AddDictAsync(string surname, int number) {
            return base.Channel.AddDictAsync(surname, number);
        }
        
        public string UpdDict(int id, string surname, int number) {
            return base.Channel.UpdDict(id, surname, number);
        }
        
        public System.Threading.Tasks.Task<string> UpdDictAsync(int id, string surname, int number) {
            return base.Channel.UpdDictAsync(id, surname, number);
        }
        
        public string DelDict(int id) {
            return base.Channel.DelDict(id);
        }
        
        public System.Threading.Tasks.Task<string> DelDictAsync(int id) {
            return base.Channel.DelDictAsync(id);
        }
    }
}
